server {
    listen 80;

    location /api/ {
        proxy_pass http://dbaas:3000/;
    }

    location /control/ {
        proxy_pass http://control:3003/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
